### ISSUE TITLE
Homebrew launcher compatible builds

### ISSUE THREAD

**Issue by henke37** [mrdanielps/r3Ddragon#3]
Because it's much simpler to just launch from the homebrew launcher

**Comment by mrdanielps** [comment]
I agree, but it's currently not possible to benefit from the new 3DS speed on ninjhax 1 / dynarec on ninjhax 2, and the old 3DS is just too slow for this. At the moment, the CIA is the only way it can run decently.

**Comment by mrdanielps** [comment]
So, an update on this. It's been possible to run libkhax on ninjhax2 for a long time already, but the reason I didn't release anything is that I thought the 3dsx build was broken, and I was too busy with class to debug it. It turns out it wasn't and my config file was the one to blame.

I've uploaded a build, so this issue can now be closed.

It doesn't work on 9.3+ yet, but it's entirely possible to replace libkhax with memchunkhax2. I'll wait until it's a little bit more stable I guess.

**Comment by neumaennl** [comment]
I just tried running it on a New 3DS XL with firmware 10.5 using menuhax. It crashes instantly when I try to start a game.

**Comment by mrdanielps** [comment]
The dynarec uses a kernelhax, so 10.4+ is not supported

**Comment by neumaennl** [comment]
just so I get this right: there is currently no way for me to run it? That's a pity :broken_heart: :cry:
